### ISSUE TITLE
Meepos clones don't get upgraded boots

### ISSUE THREAD

**Issue by Tjstretchalot** [roberthorvers/Hoard_Mode#113]
If you buy the upgraded boots on Meepo, your clones will not get it.

**Comment by DankBudd** [comment]
@Diellan  im making a fix for this in my own mod, i can hand it over to you once its done. just need to know what boots should take priority over others

dotos boot prioritys are as follows
1- Travel2
2- Travel
3- Guardian
4- Treads
5- Arcane
6- Phase
7- Tranq
8- Brown
