### ISSUE TITLE
Meepo clone boots appear and disappear when using multiple

### ISSUE THREAD

**Issue by Htresnal** [roberthorvers/Hoard_Mode#129]
When you buy a second pair of boots, other Meepos will lose their boots(stat bonus would still be there, though). Fixable by dropping boots and picking em up back.

Meepo boots stat bonus is doubled on Meepo clones(it was so when I bought an extra pair of the same boots). That means, when the main Meepo has 2x boots stat bonus, all the clones will have 3x times the bonus.

**Comment by DankBudd** [comment]
will look into the boots disappearing tomorrow, i mightve already fixed it.

the clones shouldnt benefit from multiple boots stats as if they were in their inventories, they should get the stats bonus for the one boot in their inventory + the %bonus from meepo primes stats.

if they actually are gaining more stats then they should ill try to fix it, but i dont think they are.

**Comment by DankBudd** [comment]
cant reproduce the boots disappearing (other than already known bug where volvos boot stuff will remove custom boots when meepo prime performs an action related to his inventory.. they reappear the next time the clone moves or does anything)

in my previous comment i wrote about a %bonus which is somewhat false. the clones are supposed to get 100% of meepo primes stats + their own boots stats.
_they do get the correct amount of stats_
