### ISSUE TITLE
7.06 issues & misconsistancies

### ISSUE THREAD

**Issue by Htresnal** [roberthorvers/Hoard_Mode#140]
Items:
Aether Lens
- Amplification buff should be shifted +1% at each level, or replace +5% per level step with +6% step.
- Replace HP regen buff with +125%/+150%/+175%... mana regen buff.

Urn of Shadows
- No longer heals(shows tooltip regenerating 0 hp per sec), but still damages.

Desolator 2(may deserve a rename, "Volatile Desolator")
- Still an orb effect.

Heart of Tarrasque
- Recipe should be replaced with a second Vitality booster.
- Now has 40(-5) strength bonus
- 500(+250) health bonus

Moonshard
- Stacks won't grant small night vision range bonus

Sange, Yasha and Atos
- Stat bonus should be reviewed:
Around +31 strenght,
+22 agility,
+20 intelligence
Suggesting +35 bonus to all stats.
Should not provide 350 health bonus anymore.

Scythe of Vyse
- Reduce cooldown down to 22

Shiva's Armament
- Recipe should cost 650(+50).

Vladmir's Cuirass, King's Rapier and other new item's recipe costs probably should be reviewed.

-----
Heroes:
Alchemist
- Rework Greevil's Greed to have base bonus gold as constant 4(vanilla), bonus per stack to be 4(vanilla), and bonus cap to be 20(Horde).

Bane:
Brain sap
- Has aghs upgrade to 1.5 cooldown

Fiend's Grip
- Damage tick timer is now 0.5 instead of 1.0

Chen
- Reduce cooldown of Holy Persuasion down to 10 seconds

Drow Ranger
- Frost Arrows are not a Unique Attack Modifier

Huskar
- Rescale Lifebreak to deal 34/38/42% damage

Queen of Pain
- I wonder if we can force-level the lvl25 talent for her at level 1. If we can - we can restore her dagger to vanilla.

Sand King
- Increase Sand Storm damage up to 40/60/80/100

Viper
- Reduce Viper Strike cooldown down to 60/45/30

Creeps and bosses:
- After the update, Grow causes an already annoyingly proc rich Craggy Exterior to be even more of a melee hero trap. May use a reduce on bosses.

---
Not a 7.06 problem, but I wonder if we can make Pudge's Flesh Heap to be retroactive. Make it have 5 levels and level the first one at the start. Just like Ogre Magi's Multicast.

**Comment by DankBudd** [comment]
QoP 
- if you want to do what Htresnal suggested you could probably give qop a new talent for lvl 25 and override the aoe shadow strike talent in `npc_abilities_override.txt`.
just keep the same name and change the behavior to hidden.(so its no longer considered a talent and wont show up in the ability bar or talent tree) then level it up where you give silencer his int steal and level ogre's ult. 

Drow and Bane
- i have lua abilities of Brain Sap and Frost Arrows that are up to date if you want those.

**Comment by Diellan** [comment]
I've almost done all of these things, including QoP and Pudge. All I'm missing are the brain sap and frost arrow things, so if you have that, @DankBudd , I'd appreciate them.

**Comment by DankBudd** [comment]
@Diellan made a pr for brain sap, but theres actually a problem with frost arrows. for some reason OnSpellStart and PhaseStart arent being called when its cast so theres not really a way for me to make manual casting work. (theres a method i could use in the order filter but its waaay too hacky)

**Comment by Diellan** [comment]
@DankBudd luckily, Dota Imba has a good frost arrow implementation I can
use, so I'll try that
