### ISSUE TITLE
Some aoe spells\items work no longer after a recent update

### ISSUE THREAD

**Issue by Htresnal** [roberthorvers/Hoard_Mode#146]
Recent update broke Scythe of Vyse - no longer applies hex at all.
Also, Sven's stun is no longer aoe.
Though, Wraithfire blast still works.

**Comment by DankBudd** [comment]
is that all of them that broke? i re-coded sven stun and visage soul assumption in lua. 
about to look into scythe of vyse

**Comment by DankBudd** [comment]
just played as sven, his stun seems fine to me. guess i coded that for nothing

**Comment by Htresnal** [comment]
I think I've tried to type "Wraith king's wraithfire blast", but failed miserably. Sven's skill is supposed to be 100% vanilla

**Comment by DankBudd** [comment]
sven stun is still aoe.
wraithfire blast is also still aoe.

sheepstick does hex, but only on a single unit
