### ISSUE TITLE
New gold bag handler function crash

### ISSUE THREAD

**Issue by SirPannbiff** [roberthorvers/Hoard_Mode#158]
When many gold bags drop at the same time, an error can occur which breaks further behavior of the gold bag handler due to a nil value in the FindUnitsInRadius function:
_...ota_addons\horde_mode\scripts\vscripts\itemfunctions.lua:80: attempt to index a nil value_

Easily reproducible on money creeps, if a 6-9 stack is quickly killed.

After the error occurs, automatic bag collection no longer works, and the bags need to be clicked, which causes them to go into inventory. If the inventory is full, they stack in the backpack.

**Comment by DankBudd** [comment]
you wouldnt happened to have been using bounty hunter would you?
in a game i just played only bounty hunters gold bags would not automatically be picked up.

i already knew that they can go into the backpack, i could manually check player inventories to detect this, but i felt it wasnt really a big deal.

will look into it soon and attempt a fix.
