### ISSUE TITLE
New gold bag handler significantly affects performance over time

### ISSUE THREAD

**Issue by SirPannbiff** [roberthorvers/Hoard_Mode#162]
Everything works very nicely for the first half of the game, but around 20 minutes things start getting laggy, and at 30 minutes my fps is down to 20-30 from a steady 60 that I always get. It seems that the bags leave some invisible entities after being collected, and as more and more drop over time, performance suffers dramatically. However, this only happens in parts of the map were a lot of gold bags were dropped (so the base is affected the most). If you pan the screen to an area where few to none gold bags were dropped, performance goes back to what you would expect.

**Comment by DankBudd** [comment]
i really don't think the gold bags would be causing that. there are no entities that are being created by the code i added.

i'm just storing info in a table and removing the info once its no longer needed.
i suppose its possible they aren't properly being removed from the table, resulting in longer loops as the game goes on (fractions of a second per bag).
but again, i really don't think this is the case.

Edit: just tested to make sure the info is actually being removed from the table, and it was working just fine.

**Comment by SirPannbiff** [comment]
It's the new item I've added... Sorry for suspecting your code when it was my screw-up...
