### ISSUE TITLE
urn and drums cause massive lag on purchase. they also crash

### ISSUE THREAD

**Issue by DankBudd** [roberthorvers/Hoard_Mode#166]
the lag subsides after a few seconds.

but recently they have begun getting negative charges upon use. (wasnt the case a few days ago.)
and they crash the game shortly after the lag goes away.

**Comment by SirPannbiff** [comment]
I wonder if setting initial charges to -1 is causing the problem. This was meant as a way to remove charges from drums and urn, but in a recent search across github I could only find it in the one repository I had originally adapted it from, which makes me think that it might not be a supported usage of SetInitialCharges.

**Comment by SirPannbiff** [comment]
I think the crash is unrelated, though. I believe it has something to do with part of the game files not loading properly.

**Comment by DankBudd** [comment]
it might be unrelated, idk. 
i only tested 2x after i realized they were causing lag spikes.
crashed ~1 min after using them in both tests.

edit: i know there is another crash thats unrelated. happens once per game per player. not all at the same time. dota crashing not the server.
