### ISSUE TITLE
Pugna and Rubick share max number of wards

### ISSUE THREAD

**Issue by DankBudd** [roberthorvers/Hoard_Mode#3]
currently, there can be a total of 3 of pugnas wards (at max level) on the map at a time. even if rubick steals the spell and trys to cast it. they share the total.

this makes me wonder if there are other bugs with rubick and summons, like with lone druid or visage for example. ill do some testing.

[workshop comments](http://imgur.com/i5l5Fy6)

**Comment by DankBudd** [comment]
rubick seems to work fine when stealing summons, its just pugnas wards.

**Comment by Diellan** [comment]
Can you check to see if this behavior also happens with Lycan wolves? They're coded the same way.

**Comment by DankBudd** [comment]
yeah, lycan wolves behave the same way when stolen.

id also like to note that each level of pugnas wards have seperate limits.
so you could spawn one lvl 1 ward, then level up the skill and spawn two level 2 wards in addition the level 1 ward, etc.
lycans wolves die when you try to summon lvl 2 wolves while level 1 wolves are alive, i assume this is because you tell the skill to kill the units when you recast it.

**Comment by DankBudd** [comment]
BTW, people have been wanting a skill on pugnas ward to kill the ward. so they can delete it and place a new one.
alternatively, you could make the summon ward skill kill the oldest ward and then summon a new one.
(or you could do both, like broods spinweb)
**Links for reference**
[Spin web create & destroy kv's](https://github.com/Pizzalol/SpellLibrary/tree/master/game/scripts/npc/abilities/broodmother)
[Spin web lua](https://github.com/Pizzalol/SpellLibrary/blob/master/game/scripts/vscripts/heroes/hero_broodmother/spin_web.lua)
[dummy unit](https://github.com/Pizzalol/SpellLibrary/blob/master/game/scripts/npc/units/npc_dummy_unit.txt)
