### ISSUE TITLE
Pheonix

### ISSUE THREAD

**Issue by DankBudd** [roberthorvers/Hoard_Mode#30]
**W, visual bug:**
not really sure why, but the projectile of his W has its height set to the casters height when he shoots it instead of the height of the target point.
so if pheonix is on high ground and shoots his projectile onto lower ground, it will float.

**E, healing bug**
 sunray doesnt heal allied creeps, pretty sure it does in regular doto.

**Comment by Diellan** [comment]
Have you check the W bug in regular DOTA? He has no custom powers, only renumbered ones, so nothing weird should happen that isn't "oh, i put the wrong value"

**Comment by DankBudd** [comment]
Yeah it seems like it happens in regular doto too.
