### ISSUE TITLE
the people want to know what difficulty is chosen at all times after vote

### ISSUE THREAD

**Issue by DankBudd** [roberthorvers/Hoard_Mode#53]
1. maybe have some text in top left or right corner that is see through?
2. a command that prints it in the chat? "-difficulty"
3. an info button kind of thing that opens a window that displays it? you could include stuff like credits for who made the mod or something too.

knowing the difficulty is pretty valuable information and people really want it, im sure you'll figure something out.

theres many more than just these comments
![people2](https://cloud.githubusercontent.com/assets/18477016/19710433/47fca7a8-9afc-11e6-945c-eb219a8c4442.PNG)
![people3](https://cloud.githubusercontent.com/assets/18477016/19710432/47fc7206-9afc-11e6-8f68-b11513425835.PNG)
![people](https://cloud.githubusercontent.com/assets/18477016/19710434/47ffe224-9afc-11e6-81cf-f32824cac1c4.PNG)

**Comment by Htresnal** [comment]
This issue can be closed now, I guess.
