### ISSUE TITLE
Saw your To-Do list.

### ISSUE THREAD

**Issue by DankBudd** [roberthorvers/Hoard_Mode#6]
- **_A new ultimate for Vengeful Spirit (This can be literally anything you think would be fun/useful in Horde Mode)_**  

Just give her aoe swap that deals damage. maybe something like 300/600/900
and short cd with scepter

Or if there's problems with swapping multiple units then buff up the current ultimate.
Maybe make it add base damage to heroes in an aoe around her, or even globally.
base damage because it would be amped by her vengence aura
-  **_Invoker forge spirit melting strike hits creeps_**  

I am actually making an autocasted version of melting strike already, i could make this.

**Comment by Diellan** [comment]
My plan for VS's ult was to leave it as the current single swap, but make it do AOE damage around both sides of the swap (kind of like Meepo's poof). I just haven't got around to doing it yet.

As for Forge Spirit, the problem is that I have to remake the summon (you can't override units, you have to replace them), which means digging into his entire ability set (so that Invoke will work right) via the Spell Library. It's a lot of work and room for bugs, though it will let me make some changes I want (like making Sun Strike no longer split damage, or Cold Snap into an aoe).

**Comment by DankBudd** [comment]
that idea for vengeful could work, but it kind of defeats the purpose of swapping. if it works like poof, you'd just run up to them before you swap to get the most damage.

and im kind of interested in the idea of 'remaking' an entire hero. im gunna look into invoker and see if it isnt too complicated for me.
im gunna try to remake invoker, dont really care if you use the code, i just wanna learn.

**Comment by DankBudd** [comment]
invoker actually isnt that complicated, and from what i can see, you CAN replace the ability on his summon.
`forged_spirit:RemoveAbility("forged_spirit_melting_strike")
        forged_spirit:AddAbility("forged_spirit_melting_strike_datadriven") 
        forged_spirit:FindAbilityByName("forged_spirit_melting_strike_datadriven"):SetLevel(1)`

**Comment by Diellan** [comment]
The question is "where do you fire those functions from"?

**Comment by DankBudd** [comment]
sorry, i got tunnel vision when i saw those in the spell library and assumed there was a way to do something like  `local quas_level = caster:FindAbilityByName("quas_datadriven"):GetLevel() - 1`
but with something like `FindAbilityBySlot`
guess you do need to remake the summon

**Comment by DankBudd** [comment]
i pretty much forgot about this, but i remade invoker for horde like a week ago.
tell me if you wanna use the code
also tell me if there's other changes you want made

**Sunstrike:**
now deals full damage to all targets in aoe

**Cold Snap:**
applies in an aoe
_for some weird reason the stun isnt proc'd by custom modifiers dealing damage if WTF mode is on
but i dont think that is a problem_

**Emp:**
now steals mana properly from creeps

**Forge Spirit's Melting Strike:**
now targets all units 
_i can change this to just heroes/creeps if you want_

thats all the changes i made, other than fixing a few bugs in the spell librarys outdated version.

## 

atm theres two problems in the code.
- sunstrike doesnt have the particle for the end of cast (burnt ground)
- forge spirit has 5 mana at all levels.

but i should have those fixed soon enough

EDIT:
turns out, theres nothing in lua that you can use to change the base mana of a unit.
only things i can think of to fix the mana issue is to 
- make a bunch of forged spirit units, each with a different mana pool
- just give him a static mana pool across all levels. 500 sound good..? 
- give forged spirit an inventory and items to increase  mana
