### ISSUE TITLE
upgrading Horde Stick to Horde Wand will not carry over wand charges

### ISSUE THREAD

**Issue by DankBudd** [roberthorvers/Hoard_Mode#76]

**Comment by DankBudd** [comment]
fixed by #77

**Comment by Htresnal** [comment]
There is a little cheat. You can use up your full Magic Stick, and until its cooldown is over, build it into a Magic Wand. This will restore 50(or however much charges you had) back onto your Magic Wand.
Quite a nice little thing to know.. Don't know if should be removed or not, though.. cause its barely OP.
