### ISSUE TITLE
Vlad's Cuirass occasionaly fails to provide aura

### ISSUE THREAD

**Issue by Htresnal** [roberthorvers/Hoard_Mode#99]
Sometimes that happens after death, when Cuirass is just freshly built, or when wearer has some kind or disappearing\banishing spell(e.g. Chaos Knight's ulti). It prevents the wearer from getting the aura bonuses(including lifesteal).
Ingame cure is simple - drop'n'pick, but it may catch in suprise and lose someone a game.

**Comment by DankBudd** [comment]
probably caused by DOTA_UNIT_TARGET_FLAG_INVULNERABLE in the auras

**Comment by DankBudd** [comment]
#120

**Comment by DankBudd** [comment]
not fixed
